# route schemes
bundleCreateConfig:
  request: "bundle:create-config"
  handler: "shift1:core:bundle::createConfigFromBundles"

bundleManage:
  request: "bundle:<action>"
  handler: "shift1:core:bundle::<action>"

