testroute:
  scheme: testroute/@_controller/@_action
  bindings:
    _controller:
      default: Testroutecontroller

    _action:
      default: indexvontestroute

nocontroller:
  scheme: foo/@_action/
  bindings:
    _controller:
      default: Index
    _action:
      default: index
      match: s

default:
  scheme: @_controller/@_action/
  bindings:
    _controller:
      default: Index

    _action:
      default: index
      match: .*

fallback:
  scheme:
  bindings:
    _controller:
      default: Error
    _action:
      default: index