# route schemes
aTest:
    request: ^/viewpost/<post><format>
    handler: shift1:blogDemo:post::view
    bindings:
        @post:
            paramConverter: \Bundles\Shift1\BlogDemoBundle\Routing\ParamConverter\BlogpostConverter
        @format:
            match: (\.[a-z]{3,4})
            default: html

viewpost:
    request: ^/<lang>/viewpost/<post><format>
    handler: shift1:blogDemo:post::view
    bindings:
        @post:
            paramConverter: \Bundles\Shift1\BlogDemoBundle\Routing\ParamConverter\BlogpostConverter
        @format:
            match: (\.[a-z]{3,4})
            default: html


fallback:
  request: /
  handler: shift1:core:error::notfound