# route schemes
viewpost:
  scheme: /viewpost/@post
  bindings:
    _bundle:
      default: Shift1:BlogDemo
    _controller:
      default: Post
    _action:
      default: view
    post:
      converter: \Bundles\Shift1\BlogDemoBundle\Routing\ParamConverter\BlogpostConverter

default:
  scheme: /@_bundle/@_controller/@_action/
  bindings:
    _controller:
      default: Index

    _action:
      default: index
      match: .*

fallback:
  scheme: /
  bindings:
    _bundle:
      default: CoreBundle
    _controller:
      default: Error
    _action:
      default: index
