testroute:
  scheme: testroute/@_controller/@_action
  bindings:
    _controller:
      default: Testroutecontroller

    _action:
      default: indexvontestroute

test:
  scheme: @_controller/@_action/@notused/@foo
  bindings:
    notused:
      default: 'gehtsnoch?'
    foo:
      default: 'bar'

default:
  scheme: @_controller/@_action
  bindings:
    _controller:
      default: Index

    _action:
      default: index
      match: .*

